[2020-09-09 16:17:22,057][Thread-33:5492][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2020-09-09 16:18:12,657][Thread-35:7596][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2020-09-09 16:33:24,492][Thread-93:6988][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2020-09-09 17:54:50,685][Thread-20:6244][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /blog/updown/]
[2020-09-09 17:54:53,160][Thread-21:7104][task_id:django.security.csrf][csrf.py:160][WARNING][Forbidden (CSRF token missing or incorrect.): /blog/updown/]
[2020-09-09 17:55:38,130][Thread-22:1116][task_id:django.request][exception.py:135][ERROR][Internal Server Error: /blog/yubatian/article/1/]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 507, in parse
    compile_func = self.tags[command]
KeyError: 'csrf_except'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\myblog\blog\views.py", line 150, in article_detail
    "blog":blog,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 21, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 39, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 162, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 136, in find_template
    name, template_dirs=dirs, skip=skip,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 44, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 191, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 230, in compile_nodelist
    return parser.parse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 312, in do_extends
    nodelist = parser.parse()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 515, in parse
    raise self.error(token, e)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 513, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader_tags.py", line 255, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 509, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 565, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 17: 'csrf_except', expected 'endblock'. Did you forget to register or load this tag?
[2020-09-10 11:17:23,647][Thread-1:3836][task_id:django.request][base.py:152][WARNING][Not Found: /]
[2020-09-10 11:17:34,660][Thread-4:7376][task_id:django.request][base.py:152][WARNING][Not Found: /favicon.ico]
[2020-09-10 14:21:55,469][Thread-14:3992][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:22:03,148][Thread-16:3000][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:22:05,939][Thread-18:7308][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:22:08,668][Thread-20:7384][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:23:45,777][Thread-30:6268][task_id:django.request][base.py:152][WARNING][Not Found: /indx]
[2020-09-10 14:24:19,144][Thread-46:8840][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:24:22,550][Thread-49:6540][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:24:23,735][Thread-50:7644][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:24:24,674][Thread-51:7624][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:24:25,458][Thread-52:6168][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 14:24:26,890][Thread-53:524][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:16:45,369][Thread-5:7768][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:18:19,165][Thread-1:3348][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:18:39,822][Thread-9:7488][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:18:43,052][Thread-13:8328][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:18:59,805][Thread-17:7020][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:20:56,895][Thread-34:7156][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:21:35,036][Thread-38:8880][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:25:35,330][Thread-49:3656][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:25:37,754][Thread-51:3304][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:25:40,280][Thread-54:5128][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:25:53,792][Thread-60:776][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:40:59,748][Thread-189:6692][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:43:16,245][Thread-190:8104][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:44:29,700][Thread-193:7060][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:45:31,852][Thread-196:6316][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:45:33,913][Thread-197:6576][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:46:04,330][Thread-198:8448][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:48:53,332][Thread-5:8032][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 15:50:27,980][Thread-4:7124][task_id:blog.views][views.py:124][WARNING][又有人访问不存在页面了]
[2020-09-10 16:50:45,672][Thread-4:6908][task_id:blog.views][views.py:157][WARNING][请求访问的日志归档柜式不正确!!!]
[2020-09-10 16:50:45,824][Thread-4:6908][task_id:blog.views][views.py:158][WARNING][Cannot resolve keyword 'create_time_year' into field. Choices are: article2tag, articledetail, articleupdown, category, category_id, comment, comment_count, create_time, desc, down_count, nid, tag, title, up_count, user, user_id]
